version: '3.8'
services: 
  node-webpack-react-router:
    restart: always 
    build: 
      context: .
      dockerfile: ./images/Dockerfile
    volumes: 
      - /app/node_modules
      - ./www:/app 
    ports: 
      - "3050:3000"
      - "8095:8080"
